# Generated by Django 3.2 on 2021-04-07 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emp', '0003_newdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newdata',
            name='mobile',
            field=models.IntegerField(default=587455569556656),
        ),
    ]
